theme: jekyll-theme-slate
title: COVID en Casa
description: Una guía de colaboración para el cuidado de COVID-19
google_analytics: UA-160293705-1
show_downloads: false
github:
  is_project_page: false
